New translation contributor
WordPress/wporg-gp-translation-events pull request #214
Opened 2024-04-16 12:17 UTC by trymebytes

Fixes #213 
In this PR, first time contributors will now be known as "new translation contributors". We have also updated the logic for determining who a new translation contributor is by checking if they have submitted only 10 or fewer translations.

2024-04-16 12:47 UTC, akirk requested changes
I think we should not replace the criterium of the first translation comparison because they would lose their status as soon as they have translated more than 10 translations in the course of a translation event.

2024-04-16 13:16 UTC, trymebytes commented
We can check if they have at most 10 translations by the start of the event

2024-04-17 09:01 UTC, psrpinto approved these changes
LGTM 👍

2024-04-17 12:05 UTC, akirk approved these changes

2024-04-17 12:39 UTC, merged