Clean up stats calculator
WordPress/wporg-gp-translation-events pull request #235
Opened 2024-04-29 13:58 UTC by psrpinto

- Add type hints
- Re-enable phpcs
- Extract method out of Stats_Calculator into a Project_Repository
- Extract method out of Stats_Calculator into Attendee_Repository
- Make get_attendees_not_contributing() return instances of Attendee
- Remove unneeded condition

2024-04-29 14:06 UTC, psrpinto commented on templates/event.php
> -							$_attendee = $attendee_repo->get_attendee( $event_id, $_user->ID );
This is the query that was removed.

2024-04-29 15:20 UTC, psrpinto commented on templates/event.php
> -							$_attendee = $attendee_repo->get_attendee( $event_id, $_user->ID );
This is the query that was removed.

2024-04-30 09:28 UTC, akirk requested changes
I noticed that a non-contributor is no longer detected as host:

![no-host](https://github.com/WordPress/wporg-gp-translation-events/assets/203408/74c230d2-909b-4d4c-abc2-905ee7eddb42)

Not sure why this breaks it but it works in `trunk`.

2024-04-30 14:03 UTC, psrpinto commented
I've found the cause of the issue above, working on a fix.

2024-04-30 15:23 UTC, psrpinto commented
Issue is now fixed.

2024-05-03 11:58 UTC, akirk approved these changes
Confirmed that this works now. Thanks!

2024-05-03 13:40 UTC, psrpinto commented
Thanks for testing @akirk !

2024-05-03 13:40 UTC, merged