Fix access to manage attendees page
WordPress/wporg-gp-translation-events pull request #318
Opened 2024-06-04 15:03 UTC by trymebytes

Fixes #317

2024-06-05 12:16 UTC, akirk requested changes
I think this fix goes in the wrong direction. The `edit_translation_event_attendees` should be used here. What should happen in this PR is to not show the button if the user doesn't have the permission, i.e.
```diff
diff --git i/templates/event-edit.php w/templates/event-edit.php
index 334a8c6..4bbb104 100644
--- i/templates/event-edit.php
+++ w/templates/event-edit.php
@@ -28,7 +28,9 @@ Templates::header(
 </div>
 
 <div class="event-edit-right">
+	<?php if ( current_user_can( 'edit_translation_event_attendees', $event->id() ) ) : ?>
 		<a class="manage-attendees-btn button is-primary" href="<?php echo esc_url( Urls::event_attendees( $event->id() ) ); ?>"><?php esc_html_e( 'Manage Attendees', 'gp-translation-events' ); ?></a>
+	<?php endif; ?>
 </div>
 
 <?php Templates::footer(); ?>
```

2024-06-05 15:04 UTC, trymebytes commented
Thank you Alex, Jesús and I also talked about this.

2024-06-06 08:43 UTC, psrpinto approved these changes
👍

2024-06-10 08:49 UTC, akirk approved these changes
Thank you!

2024-06-10 09:01 UTC, merged