Register an user to attend or un-attend to an event
WordPress/wporg-gp-translation-events pull request #60
Opened 2024-02-13 09:19 UTC by amieiro

The [Attend or un-attend an event #43](https://github.com/WordPress/wporg-gp-translation-events/pull/43) PR tried to merge into the [filter-style-list](https://github.com/WordPress/wporg-gp-translation-events/tree/filter-style-list) branch, not in the trunk branch, but we merge [the PR](https://github.com/WordPress/wporg-gp-translation-events/pull/36) for this [filter-style-list](https://github.com/WordPress/wporg-gp-translation-events/tree/filter-style-list) branch before we approve the [#43](https://github.com/WordPress/wporg-gp-translation-events/pull/43) PR, so the code was not merged in the trunk branch, and now it has a lot of merge conflicts. 

This PR resolve the merging conflicts and add the same functionality than #43.

2024-02-13 13:23 UTC, psrpinto requested changes
Thanks for fixing the conflicts. I noticed a couple of things that I think need to be fixed.

2024-02-13 13:23 UTC, psrpinto commented on includes/class-wporg-gp-translation-events-route.php
> +		$event_end           = get_post_meta( $event->ID, '_event_end', true ) ?? '';
Should be `?:` instead of `??`.

2024-02-13 13:23 UTC, psrpinto commented on includes/class-wporg-gp-translation-events-route.php
> +		$event_project_name  = get_post_meta( $event->ID, '_event_project_name', true ) ?: '';
Project name and locale have been removed now, they're being added back here.

2024-02-14 08:04 UTC, amieiro commented on includes/class-wporg-gp-translation-events-route.php
> +		$event_end           = get_post_meta( $event->ID, '_event_end', true ) ?? '';
I think it is correct. This is the [Null coalescing operator](https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op). If `get_post_meta( $event->ID, '_event_start', true )` returns a valid value, `$event_start = get_post_meta( $event->ID, '_event_start', true )`. If it returns `false`, then  `$event_start = ''`.

2024-02-14 08:23 UTC, amieiro commented on includes/class-wporg-gp-translation-events-route.php
> +		$event_project_name  = get_post_meta( $event->ID, '_event_project_name', true ) ?: '';
Yes, we don't need it. Removed [here](https://github.com/WordPress/wporg-gp-translation-events/pull/60/commits/2c027c424cc911dfa5b86c4cb03aadaf3ea31bac). Thank you!

2024-02-14 11:56 UTC, psrpinto commented on includes/class-wporg-gp-translation-events-route.php
> +		$event_end           = get_post_meta( $event->ID, '_event_end', true ) ?? '';
Ok, I see. We changed this from `??` to `?:` because of [this remark](https://github.com/WordPress/wporg-gp-translation-events/pull/43#discussion_r1484308260), but now I'm not sure anymore. Should we change the other conditions below to also use `??`?

2024-02-14 13:16 UTC, trymebytes approved these changes
Looks good to me!

2024-02-14 13:45 UTC, psrpinto approved these changes

2024-02-15 01:16 UTC, amieiro commented on includes/class-wporg-gp-translation-events-route.php
> +		$event_end           = get_post_meta( $event->ID, '_event_end', true ) ?? '';
Yes, you are right. The `get_post_meta( something, something, true )` can return:
- The value of the metadata field.
- A false value.
- An empty string.

So the correct usage is `?:`. Removed [here](https://github.com/WordPress/wporg-gp-translation-events/pull/60/commits/9e80788583af709404001977a8e1920dd7c33ced). You can test it easily with this code:

```
<?php 
echo 1 ?? 'a';
echo false ?? 'b';
echo '' ?? 'c';

echo 1 ?: 'd';
echo false ?: 'e';
echo '' ?: 'f';
```

2024-02-15 01:21 UTC, merged